"""
Distributional validation of pystatistics MICE against R's `mice` (3.19.0).

We do NOT reproduce R's RNG stream. MICE is stochastic; the correctness story is
that pystatistics uses the same defaults and algorithm as R and therefore
produces the same *statistical behaviour*. So we impute the identical incomplete
dataset (mice_validation_data.csv) with the same settings and check that:

  * the distribution of imputed values per column matches R's in mean, spread,
    and quantiles (within Monte-Carlo tolerance), and
  * a Rubin's-rules pooled regression agrees with R's `pool()` output.

Reference fixtures are generated by ``generate_mice_fixtures.R`` (pinned to
mice 3.19.0). If they are absent, these tests skip.
"""

import json
from pathlib import Path

import numpy as np
import pytest

from pystatistics.mice import mice, pool

REF_DIR = Path(__file__).parent / "references"
REF_JSON = REF_DIR / "mice_reference.json"
DATA_CSV = REF_DIR / "mice_validation_data.csv"

pytestmark = pytest.mark.skipif(
    not REF_JSON.exists() or not DATA_CSV.exists(),
    reason="R mice reference fixtures not present (run generate_mice_fixtures.R)",
)


@pytest.fixture(scope="module")
def reference():
    with open(REF_JSON) as f:
        return json.load(f)


@pytest.fixture(scope="module")
def incomplete():
    return np.genfromtxt(DATA_CSV, delimiter=",", names=True)  # structured


@pytest.fixture(scope="module")
def incomplete_matrix():
    # Plain (n, 3) float matrix with NaN for missing.
    return np.genfromtxt(DATA_CSV, delimiter=",", skip_header=1)


def _our_solution(matrix, method, ref):
    meta = ref["meta"]
    return mice(
        matrix,
        n_imputations=meta["m"],
        max_iter=meta["maxit"],
        method=method,
        seed=20260614,
    )


@pytest.mark.parametrize("method", ["pmm", "norm"])
class TestImputedValueDistributions:
    def test_imputed_mean_matches_r(self, method, reference, incomplete_matrix):
        sol = _our_solution(incomplete_matrix, method, reference)
        per_col = reference[method]["per_col"]
        for col_idx, col_name in enumerate(reference["meta"]["incomplete_columns"]):
            ours = sol.imputations(col_idx).ravel()
            r_mean = per_col[col_name]["imputed_mean"]
            # Monte-Carlo tolerance: SE of mean ~ sd/sqrt(N); generous 3-sigma+.
            assert ours.mean() == pytest.approx(r_mean, abs=0.15), (
                f"{method} {col_name}: our mean {ours.mean():.4f} vs R {r_mean:.4f}"
            )

    def test_imputed_sd_matches_r(self, method, reference, incomplete_matrix):
        sol = _our_solution(incomplete_matrix, method, reference)
        per_col = reference[method]["per_col"]
        for col_idx, col_name in enumerate(reference["meta"]["incomplete_columns"]):
            ours = sol.imputations(col_idx).ravel()
            r_sd = per_col[col_name]["imputed_sd"]
            assert ours.std(ddof=1) == pytest.approx(r_sd, rel=0.20), (
                f"{method} {col_name}: our sd {ours.std(ddof=1):.4f} vs R {r_sd:.4f}"
            )

    def test_imputed_quantiles_match_r(self, method, reference, incomplete_matrix):
        sol = _our_solution(incomplete_matrix, method, reference)
        per_col = reference[method]["per_col"]
        qs = [10, 25, 50, 75, 90]
        for col_idx, col_name in enumerate(reference["meta"]["incomplete_columns"]):
            ours = sol.imputations(col_idx).ravel()
            r_vals = np.asarray(per_col[col_name]["imputed"], dtype=float)
            our_q = np.percentile(ours, qs)
            r_q = np.percentile(r_vals, qs)
            # Quantiles of the imputed-value distribution should track R's.
            np.testing.assert_allclose(our_q, r_q, atol=0.4, err_msg=(
                f"{method} {col_name} quantiles differ: ours={our_q} R={r_q}"
            ))


class TestPmmDonorProperty:
    def test_pmm_imputes_only_observed_values(self, reference, incomplete_matrix):
        # R pmm and ours both copy observed donor values; verify ours never
        # synthesizes a value outside the observed set (the defining property).
        sol = _our_solution(incomplete_matrix, "pmm", reference)
        for col_idx in range(incomplete_matrix.shape[1]):
            col = incomplete_matrix[:, col_idx]
            observed = set(np.round(col[~np.isnan(col)], 8))
            for v in sol.imputations(col_idx).ravel():
                assert round(float(v), 8) in observed


def _pooled_lm(sol, df_complete):
    """Pool lm(x0 ~ x1 + x2) across completed datasets with Rubin's rules."""
    estimates, variances = [], []
    for d in sol.completed_datasets():
        X = np.column_stack([np.ones(d.shape[0]), d[:, 1], d[:, 2]])
        y = d[:, 0]
        beta, *_ = np.linalg.lstsq(X, y, rcond=None)
        resid = y - X @ beta
        sigma2 = resid @ resid / (d.shape[0] - X.shape[1])
        cov = sigma2 * np.linalg.inv(X.T @ X)
        estimates.append(beta)
        variances.append(np.diag(cov))
    return pool(np.array(estimates), np.array(variances), df_complete=df_complete)


@pytest.mark.parametrize("method", ["pmm", "norm"])
class TestPooledRegression:
    def test_pooled_estimates_match_r(self, method, reference, incomplete_matrix):
        sol = _our_solution(incomplete_matrix, method, reference)
        n = incomplete_matrix.shape[0]
        res = _pooled_lm(sol, df_complete=n - 3)

        r_pool = reference[method]["pooled_lm_x0"]
        r_est = np.asarray(r_pool["estimate"], dtype=float)
        # Stochastic with independent RNG streams: estimates agree within MC error.
        np.testing.assert_allclose(
            np.asarray(res.estimate), r_est, atol=0.1,
            err_msg=f"{method}: pooled estimates ours={res.estimate} R={r_est}",
        )

    def test_pooled_std_errors_comparable(self, method, reference, incomplete_matrix):
        sol = _our_solution(incomplete_matrix, method, reference)
        n = incomplete_matrix.shape[0]
        res = _pooled_lm(sol, df_complete=n - 3)
        r_se = np.asarray(reference[method]["pooled_lm_x0"]["std.error"], dtype=float)
        # SEs include between-imputation variance, so looser tolerance.
        np.testing.assert_allclose(
            np.asarray(res.standard_errors), r_se, rtol=0.5,
            err_msg=f"{method}: pooled SEs ours={res.standard_errors} R={r_se}",
        )
