"""
Generate test fixtures for Monte Carlo validation against R's boot package.

Creates ~10 scenarios with fixed seeds, covering:
- Bootstrap: ordinary, balanced, parametric
- Bootstrap CI: all 5 methods
- Permutation test: two-sided, one-sided, symmetric

Fixture format:
    mc_{name}_meta.json     - data + call parameters
    mc_{name}_r_results.json - generated by run_r_montecarlo_validation.R

Usage:
    python tests/fixtures/generate_montecarlo_fixtures.py
    Rscript tests/fixtures/run_r_montecarlo_validation.R
    pytest tests/montecarlo/test_r_validation.py -v
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

FIXTURES_DIR = Path(__file__).resolve().parent


def _save_meta(name: str, meta: dict) -> None:
    """Save fixture metadata as JSON."""
    path = FIXTURES_DIR / f"mc_{name}_meta.json"
    with open(path, "w") as f:
        json.dump(meta, f, indent=2, default=_json_default)
    print(f"  Saved {path.name}")


def _json_default(obj):
    """JSON serializer for numpy types."""
    if isinstance(obj, np.ndarray):
        return obj.tolist()
    if isinstance(obj, np.integer):
        return int(obj)
    if isinstance(obj, np.floating):
        return float(obj)
    raise TypeError(f"Object of type {type(obj)} is not JSON serializable")


# ---------------------------------------------------------------------------
# Bootstrap fixtures
# ---------------------------------------------------------------------------

def make_boot_mean_ordinary():
    """Ordinary bootstrap for the mean — simplest case."""
    rng = np.random.default_rng(42)
    data = rng.normal(5.0, 2.0, 30)

    _save_meta("boot_mean_ordinary", {
        "type": "boot",
        "data": data,
        "R": 999,
        "sim": "ordinary",
        "stype": "i",
        "seed": 42,
        "description": "Ordinary bootstrap for sample mean, n=30",
    })


def make_boot_mean_balanced():
    """Balanced bootstrap for the mean."""
    rng = np.random.default_rng(42)
    data = rng.normal(5.0, 2.0, 30)

    _save_meta("boot_mean_balanced", {
        "type": "boot",
        "data": data,
        "R": 999,
        "sim": "balanced",
        "stype": "i",
        "seed": 42,
        "description": "Balanced bootstrap for sample mean, n=30",
    })


def make_boot_variance():
    """Bootstrap for sample variance (skewed statistic)."""
    rng = np.random.default_rng(123)
    data = rng.exponential(2.0, 50)

    _save_meta("boot_variance", {
        "type": "boot",
        "data": data,
        "R": 1999,
        "sim": "ordinary",
        "stype": "i",
        "seed": 123,
        "description": "Bootstrap for sample variance, exponential data, n=50",
    })


def make_boot_median():
    """Bootstrap for the median."""
    rng = np.random.default_rng(77)
    data = rng.normal(10.0, 3.0, 40)

    _save_meta("boot_median", {
        "type": "boot",
        "data": data,
        "R": 999,
        "sim": "ordinary",
        "stype": "i",
        "seed": 77,
        "description": "Bootstrap for sample median, n=40",
    })


# ---------------------------------------------------------------------------
# Bootstrap CI fixtures
# ---------------------------------------------------------------------------

def make_boot_ci_normal():
    """Bootstrap CI (all types) for the mean of normal data."""
    rng = np.random.default_rng(42)
    data = rng.normal(5.0, 2.0, 50)

    _save_meta("boot_ci_normal", {
        "type": "boot_ci",
        "data": data,
        "R": 2999,
        "sim": "ordinary",
        "stype": "i",
        "seed": 42,
        "conf_level": 0.95,
        "ci_types": ["normal", "basic", "perc", "bca"],
        "description": "Bootstrap CI (4 types) for mean, normal data, n=50",
    })


def make_boot_ci_skewed():
    """Bootstrap CI for the mean of skewed data (BCa should differ from perc)."""
    rng = np.random.default_rng(55)
    data = rng.exponential(2.0, 60)

    _save_meta("boot_ci_skewed", {
        "type": "boot_ci",
        "data": data,
        "R": 2999,
        "sim": "ordinary",
        "stype": "i",
        "seed": 55,
        "conf_level": 0.95,
        "ci_types": ["normal", "basic", "perc", "bca"],
        "description": "Bootstrap CI for mean, exponential data (skewed), n=60",
    })


def make_boot_ci_90():
    """Bootstrap CI at 90% confidence."""
    rng = np.random.default_rng(42)
    data = rng.normal(10.0, 1.0, 100)

    _save_meta("boot_ci_90", {
        "type": "boot_ci",
        "data": data,
        "R": 2999,
        "sim": "ordinary",
        "stype": "i",
        "seed": 42,
        "conf_level": 0.90,
        "ci_types": ["normal", "basic", "perc", "bca"],
        "description": "Bootstrap CI (90%) for mean, normal data, n=100",
    })


# ---------------------------------------------------------------------------
# Permutation test fixtures
# ---------------------------------------------------------------------------

def make_perm_significant():
    """Permutation test with significant difference (two-sided)."""
    rng = np.random.default_rng(42)
    x = rng.normal(0.0, 1.0, 30)
    y = rng.normal(2.0, 1.0, 30)

    _save_meta("perm_significant", {
        "type": "permutation",
        "x": x,
        "y": y,
        "R": 9999,
        "alternative": "two.sided",
        "seed": 42,
        "description": "Permutation test, significant difference, two-sided",
    })


def make_perm_not_significant():
    """Permutation test with no significant difference."""
    rng = np.random.default_rng(42)
    x = rng.normal(0.0, 1.0, 30)
    y = rng.normal(0.0, 1.0, 30)

    _save_meta("perm_not_significant", {
        "type": "permutation",
        "x": x,
        "y": y,
        "R": 9999,
        "alternative": "two.sided",
        "seed": 42,
        "description": "Permutation test, no significant difference",
    })


def make_perm_greater():
    """Permutation test, one-sided (greater)."""
    rng = np.random.default_rng(99)
    x = rng.normal(3.0, 1.0, 25)
    y = rng.normal(1.0, 1.0, 25)

    _save_meta("perm_greater", {
        "type": "permutation",
        "x": x,
        "y": y,
        "R": 9999,
        "alternative": "greater",
        "seed": 99,
        "description": "Permutation test, one-sided greater",
    })


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    print("Generating Monte Carlo fixtures...\n")

    print("Bootstrap fixtures:")
    make_boot_mean_ordinary()
    make_boot_mean_balanced()
    make_boot_variance()
    make_boot_median()

    print("\nBootstrap CI fixtures:")
    make_boot_ci_normal()
    make_boot_ci_skewed()
    make_boot_ci_90()

    print("\nPermutation test fixtures:")
    make_perm_significant()
    make_perm_not_significant()
    make_perm_greater()

    print(f"\nDone. Generated 10 fixtures in {FIXTURES_DIR}")
    print("\nNext: Rscript tests/fixtures/run_r_montecarlo_validation.R")


if __name__ == "__main__":
    main()
