"""
Generate test fixtures for survival analysis validation against R's survival package.

Creates scenarios covering:
- Kaplan-Meier: basic, censored, ties, CI types
- Log-rank test: two-group, three-group, G-rho
- Cox PH: single covariate, multi-covariate, Efron/Breslow ties

Fixture format:
    surv_{name}_meta.json     - data + call parameters
    surv_{name}_r_results.json - generated by run_r_survival_validation.R

Usage:
    python tests/fixtures/generate_survival_fixtures.py
    Rscript tests/fixtures/run_r_survival_validation.R
    pytest tests/survival/test_r_validation.py -v
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

FIXTURES_DIR = Path(__file__).resolve().parent


def _save_meta(name: str, meta: dict) -> None:
    """Save fixture metadata as JSON."""
    path = FIXTURES_DIR / f"surv_{name}_meta.json"
    with open(path, "w") as f:
        json.dump(meta, f, indent=2, default=_json_default)
    print(f"  Saved {path.name}")


def _json_default(obj):
    """JSON serializer for numpy types."""
    if isinstance(obj, np.ndarray):
        return obj.tolist()
    if isinstance(obj, np.integer):
        return int(obj)
    if isinstance(obj, np.floating):
        return float(obj)
    raise TypeError(f"Object of type {type(obj)} is not JSON serializable")


# ---------------------------------------------------------------------------
# Kaplan-Meier fixtures
# ---------------------------------------------------------------------------

def km_basic():
    """Basic KM curve with censoring."""
    _save_meta("km_basic", {
        "type": "kaplan_meier",
        "time": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        "event": [1, 1, 0, 1, 1, 0, 1, 1, 0, 1],
        "conf_level": 0.95,
        "conf_type": "log",
    })


def km_no_censoring():
    """All events (no censoring)."""
    _save_meta("km_no_cens", {
        "type": "kaplan_meier",
        "time": [2, 4, 6, 8, 10, 12, 14, 16, 18, 20],
        "event": [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        "conf_level": 0.95,
        "conf_type": "log",
    })


def km_heavy_censoring():
    """Heavy censoring (70% censored)."""
    _save_meta("km_heavy_cens", {
        "type": "kaplan_meier",
        "time": [1, 3, 5, 7, 9, 2, 4, 6, 8, 10,
                 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
        "event": [1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
                  0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
        "conf_level": 0.95,
        "conf_type": "log",
    })


def km_tied_events():
    """Tied event times."""
    _save_meta("km_ties", {
        "type": "kaplan_meier",
        "time": [1, 1, 2, 2, 3, 3, 4, 4, 5, 5],
        "event": [1, 0, 1, 1, 0, 1, 1, 0, 1, 1],
        "conf_level": 0.95,
        "conf_type": "log",
    })


def km_plain_ci():
    """KM with plain CI."""
    _save_meta("km_plain_ci", {
        "type": "kaplan_meier",
        "time": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        "event": [1, 1, 0, 1, 1, 0, 1, 1, 0, 1],
        "conf_level": 0.95,
        "conf_type": "plain",
    })


def km_loglog_ci():
    """KM with log-log CI."""
    _save_meta("km_loglog_ci", {
        "type": "kaplan_meier",
        "time": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        "event": [1, 1, 0, 1, 1, 0, 1, 1, 0, 1],
        "conf_level": 0.95,
        "conf_type": "log-log",
    })


# ---------------------------------------------------------------------------
# Log-rank test fixtures
# ---------------------------------------------------------------------------

def logrank_two_group():
    """Two-group log-rank test."""
    _save_meta("lr_two_group", {
        "type": "logrank",
        "time": [6, 7, 10, 15, 16, 22, 23, 6, 9, 10, 11, 17, 19, 20],
        "event": [1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1],
        "group": [1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2],
        "rho": 0.0,
    })


def logrank_three_group():
    """Three-group log-rank test."""
    _save_meta("lr_three_group", {
        "type": "logrank",
        "time": [1, 2, 3, 4, 5, 6, 1, 3, 5, 7, 9, 11, 2, 4, 6, 8, 10, 12],
        "event": [1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1],
        "group": [1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3],
        "rho": 0.0,
    })


def logrank_peto():
    """Peto-Peto test (rho=1)."""
    _save_meta("lr_peto", {
        "type": "logrank",
        "time": [6, 7, 10, 15, 16, 22, 23, 6, 9, 10, 11, 17, 19, 20],
        "event": [1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1],
        "group": [1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2],
        "rho": 1.0,
    })


# ---------------------------------------------------------------------------
# Cox PH fixtures
# ---------------------------------------------------------------------------

def cox_single_covariate():
    """Cox PH with one continuous covariate (well-behaved)."""
    rng = np.random.default_rng(42)
    n = 30
    x = rng.standard_normal(n)
    # Generate survival times correlated with x
    time = rng.exponential(np.exp(-0.5 * x))
    event = rng.binomial(1, 0.7, n).astype(float)
    # Ensure at least some events
    event[:10] = 1.0

    _save_meta("cox_single", {
        "type": "coxph",
        "time": time.tolist(),
        "event": event.tolist(),
        "X": x.reshape(-1, 1).tolist(),
        "ties": "efron",
    })


def cox_two_covariates():
    """Cox PH with two covariates."""
    rng = np.random.default_rng(123)
    n = 40
    x1 = rng.standard_normal(n)
    x2 = rng.binomial(1, 0.5, n).astype(float)
    time = rng.exponential(np.exp(-0.3 * x1 + 0.5 * x2))
    event = rng.binomial(1, 0.65, n).astype(float)
    event[:15] = 1.0

    _save_meta("cox_two_cov", {
        "type": "coxph",
        "time": time.tolist(),
        "event": event.tolist(),
        "X": np.column_stack([x1, x2]).tolist(),
        "ties": "efron",
    })


def cox_breslow():
    """Cox PH with Breslow ties."""
    rng = np.random.default_rng(42)
    n = 30
    x = rng.standard_normal(n)
    time = rng.exponential(np.exp(-0.5 * x))
    event = rng.binomial(1, 0.7, n).astype(float)
    event[:10] = 1.0

    _save_meta("cox_breslow", {
        "type": "coxph",
        "time": time.tolist(),
        "event": event.tolist(),
        "X": x.reshape(-1, 1).tolist(),
        "ties": "breslow",
    })


def cox_tied_times():
    """Cox PH with tied event times (Efron)."""
    _save_meta("cox_ties", {
        "type": "coxph",
        "time": [1, 1, 2, 2, 3, 3, 4, 4, 5, 5,
                 6, 6, 7, 7, 8, 8, 9, 9, 10, 10],
        "event": [1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
                  0, 1, 1, 0, 1, 1, 0, 1, 1, 0],
        "X": [[0.5], [-0.3], [0.8], [-0.5], [1.0], [-1.2], [0.3], [0.7],
              [-0.8], [1.5], [-0.2], [0.4], [-1.0], [0.9], [-0.6], [1.1],
              [-0.4], [0.2], [-0.1], [0.6]],
        "ties": "efron",
    })


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    print("Generating survival fixtures...")

    print("\n  Kaplan-Meier:")
    km_basic()
    km_no_censoring()
    km_heavy_censoring()
    km_tied_events()
    km_plain_ci()
    km_loglog_ci()

    print("\n  Log-rank:")
    logrank_two_group()
    logrank_three_group()
    logrank_peto()

    print("\n  Cox PH:")
    cox_single_covariate()
    cox_two_covariates()
    cox_breslow()
    cox_tied_times()

    print(f"\nGenerated 13 fixture files in {FIXTURES_DIR}")
    print("Next: run Rscript tests/fixtures/run_r_survival_validation.R")


if __name__ == "__main__":
    main()
