#!/usr/bin/env Rscript
#
# Run R ANOVA analyses on fixtures generated by generate_anova_fixtures.py
#
# Usage:
#   Rscript tests/fixtures/run_r_anova_validation.R
#
# Reads anova_*_meta.json files, runs R analyses, writes anova_*_r_results.json.
#
# Required R packages: car, ez (for repeated measures), effectsize
# Install: install.packages(c("car", "jsonlite"))
# Optional: install.packages(c("ez", "effectsize", "DescTools"))

library(jsonlite)

# Determine script directory
args <- commandArgs(trailingOnly = FALSE)
file_arg <- grep("^--file=", args, value = TRUE)
if (length(file_arg) > 0) {
  script_dir <- normalizePath(dirname(sub("^--file=", "", file_arg)))
} else {
  script_dir <- normalizePath("tests/fixtures")
}

cat("Fixture directory:", script_dir, "\n\n")

# Find all anova_*_meta.json files
meta_files <- list.files(script_dir, pattern = "^anova_.*_meta\\.json$", full.names = TRUE)

if (length(meta_files) == 0) {
  cat("No anova_*_meta.json files found. Run generate_anova_fixtures.py first.\n")
  quit(status = 1)
}

cat("Found", length(meta_files), "fixture files\n\n")

for (mf in meta_files) {
  name <- sub("_meta\\.json$", "", basename(mf))
  name <- sub("^anova_", "", name)
  cat("Processing:", name, "...")

  meta <- fromJSON(mf)
  result <- list()

  if (meta$type == "oneway") {
    # ── One-way ANOVA ──
    y <- as.numeric(meta$y)
    g <- factor(meta$group)
    df <- data.frame(y = y, group = g)

    # Type I (default R)
    fit <- lm(y ~ group, data = df)
    tbl <- anova(fit)

    result$type1_df <- tbl$Df
    result$type1_ss <- tbl$`Sum Sq`
    result$type1_ms <- tbl$`Mean Sq`
    result$type1_f <- tbl$`F value`[1]
    result$type1_p <- tbl$`Pr(>F)`[1]

    # Type II (car)
    if (requireNamespace("car", quietly = TRUE)) {
      tbl2 <- car::Anova(fit, type = "II")
      result$type2_ss_group <- tbl2$`Sum Sq`[1]
      result$type2_f_group <- tbl2$`F value`[1]
      result$type2_p_group <- tbl2$`Pr(>F)`[1]
    }

    # Type III (car with contr.sum)
    if (requireNamespace("car", quietly = TRUE)) {
      df3 <- df
      contrasts(df3$group) <- contr.sum
      fit3 <- lm(y ~ group, data = df3)
      tbl3 <- car::Anova(fit3, type = "III")
      # Type III: first row is Intercept, second is group
      result$type3_ss_group <- tbl3$`Sum Sq`[2]
      result$type3_f_group <- tbl3$`F value`[2]
      result$type3_p_group <- tbl3$`Pr(>F)`[2]
    }

    result$residual_df <- tbl$Df[2]
    result$residual_ss <- tbl$`Sum Sq`[2]

    cat(" oneway OK\n")

  } else if (meta$type == "factorial") {
    # ── Factorial ANOVA ──
    y <- as.numeric(meta$y)
    A <- factor(meta$factor_A)
    B <- factor(meta$factor_B)
    df <- data.frame(y = y, A = A, B = B)

    fit <- lm(y ~ A * B, data = df)

    # Type I
    tbl1 <- anova(fit)
    result$type1_terms <- rownames(tbl1)
    result$type1_df <- tbl1$Df
    result$type1_ss <- tbl1$`Sum Sq`
    result$type1_ms <- tbl1$`Mean Sq`
    result$type1_f <- tbl1$`F value`
    result$type1_p <- tbl1$`Pr(>F)`

    # Type II
    if (requireNamespace("car", quietly = TRUE)) {
      tbl2 <- car::Anova(fit, type = "II")
      result$type2_terms <- rownames(tbl2)
      result$type2_ss <- tbl2$`Sum Sq`
      result$type2_f <- tbl2$`F value`
      result$type2_p <- tbl2$`Pr(>F)`
    }

    # Type III
    if (requireNamespace("car", quietly = TRUE)) {
      df3 <- df
      contrasts(df3$A) <- contr.sum
      contrasts(df3$B) <- contr.sum
      fit3 <- lm(y ~ A * B, data = df3)
      tbl3 <- car::Anova(fit3, type = "III")
      result$type3_terms <- rownames(tbl3)
      result$type3_ss <- tbl3$`Sum Sq`
      result$type3_f <- tbl3$`F value`
      result$type3_p <- tbl3$`Pr(>F)`
    }

    result$residual_df <- tail(tbl1$Df, 1)
    result$residual_ss <- tail(tbl1$`Sum Sq`, 1)

    cat(" factorial OK\n")

  } else if (meta$type == "ancova") {
    # ── ANCOVA ──
    y <- as.numeric(meta$y)
    g <- factor(meta$group)
    x <- as.numeric(meta$covariate)
    df <- data.frame(y = y, group = g, x = x)

    fit <- lm(y ~ group + x, data = df)

    # Type II
    if (requireNamespace("car", quietly = TRUE)) {
      tbl2 <- car::Anova(fit, type = "II")
      result$type2_terms <- rownames(tbl2)
      result$type2_ss <- tbl2$`Sum Sq`
      result$type2_f <- tbl2$`F value`
      result$type2_p <- tbl2$`Pr(>F)`
      result$residual_df <- tbl2$Df[nrow(tbl2)]
      result$residual_ss <- tbl2$`Sum Sq`[nrow(tbl2)]
    }

    cat(" ancova OK\n")

  } else if (meta$type == "levene") {
    # ── Levene test ──
    y <- as.numeric(meta$y)
    g <- factor(meta$group)

    if (requireNamespace("car", quietly = TRUE)) {
      # Brown-Forsythe (center=median, R's default)
      lev_med <- car::leveneTest(y ~ g, center = median)
      result$bf_f <- lev_med$`F value`[1]
      result$bf_p <- lev_med$`Pr(>F)`[1]
      result$bf_df1 <- lev_med$Df[1]
      result$bf_df2 <- lev_med$Df[2]

      # Original Levene (center=mean)
      lev_mean <- car::leveneTest(y ~ g, center = mean)
      result$levene_f <- lev_mean$`F value`[1]
      result$levene_p <- lev_mean$`Pr(>F)`[1]
    }

    cat(" levene OK\n")

  } else if (meta$type == "tukey") {
    # ── Tukey HSD ──
    y <- as.numeric(meta$y)
    g <- factor(meta$group)
    df <- data.frame(y = y, group = g)

    fit <- aov(y ~ group, data = df)
    tukey <- TukeyHSD(fit)$group

    result$comparisons <- rownames(tukey)
    result$diff <- tukey[, "diff"]
    result$lwr <- tukey[, "lwr"]
    result$upr <- tukey[, "upr"]
    result$p_adj <- tukey[, "p adj"]

    cat(" tukey OK\n")

  } else if (meta$type == "bonferroni") {
    # ── Bonferroni pairwise ──
    y <- as.numeric(meta$y)
    g <- factor(meta$group)

    pw <- pairwise.t.test(y, g, p.adjust.method = "bonferroni", pool.sd = TRUE)
    result$p_values <- as.list(pw$p.value)
    result$method <- "bonferroni"

    cat(" bonferroni OK\n")

  } else if (meta$type == "rm_within") {
    # ── Repeated measures (within only) ──
    y <- as.numeric(meta$y)
    subj <- factor(meta$subject)
    cond <- factor(meta$condition)
    df <- data.frame(y = y, subject = subj, condition = cond)

    # Base R approach
    fit <- aov(y ~ condition + Error(subject/condition), data = df)
    s <- summary(fit)

    # Within-subject error term
    within_tbl <- s$`Error: subject:condition`[[1]]
    result$within_term <- "condition"
    result$within_df <- within_tbl$Df[1]
    result$within_ss <- within_tbl$`Sum Sq`[1]
    result$within_ms <- within_tbl$`Mean Sq`[1]
    result$within_f <- within_tbl$`F value`[1]
    result$within_p <- within_tbl$`Pr(>F)`[1]
    result$error_df <- within_tbl$Df[2]
    result$error_ss <- within_tbl$`Sum Sq`[2]
    result$error_ms <- within_tbl$`Mean Sq`[2]

    # Mauchly test + corrections via ez if available
    if (requireNamespace("ez", quietly = TRUE)) {
      ez_result <- ez::ezANOVA(
        data = df, dv = y, wid = subject, within = .(condition),
        detailed = TRUE, type = 2
      )
      if (!is.null(ez_result$`Mauchly's Test for Sphericity`)) {
        mauchly <- ez_result$`Mauchly's Test for Sphericity`
        result$mauchly_w <- mauchly$W
        result$mauchly_p <- mauchly$p
      }
      if (!is.null(ez_result$`Sphericity Corrections`)) {
        corr <- ez_result$`Sphericity Corrections`
        result$gg_epsilon <- corr$GGe
        result$hf_epsilon <- corr$HFe
        result$gg_p <- corr$`p[GG]`
        result$hf_p <- corr$`p[HF]`
      }
    }

    cat(" rm_within OK\n")

  } else if (meta$type == "rm_mixed") {
    # ── Mixed design ──
    y <- as.numeric(meta$y)
    subj <- factor(meta$subject)
    within <- factor(meta$within)
    between <- factor(meta$between)
    df <- data.frame(y = y, subject = subj, within = within, between = between)

    if (requireNamespace("ez", quietly = TRUE)) {
      ez_result <- ez::ezANOVA(
        data = df, dv = y, wid = subject,
        within = .(within), between = .(between),
        detailed = TRUE, type = 2
      )
      anova_tbl <- ez_result$ANOVA
      result$terms <- anova_tbl$Effect
      result$df_num <- anova_tbl$DFn
      result$df_den <- anova_tbl$DFd
      result$ss <- anova_tbl$SSn
      result$ss_den <- anova_tbl$SSd
      result$f <- anova_tbl$F
      result$p <- anova_tbl$p

      if (!is.null(ez_result$`Sphericity Corrections`)) {
        corr <- ez_result$`Sphericity Corrections`
        result$gg_epsilon <- corr$GGe
        result$hf_epsilon <- corr$HFe
        result$gg_p <- corr$`p[GG]`
        result$hf_p <- corr$`p[HF]`
      }
    }

    cat(" rm_mixed OK\n")

  } else if (meta$type == "eta") {
    # ── Effect sizes ──
    y <- as.numeric(meta$y)
    g <- factor(meta$group)
    df <- data.frame(y = y, group = g)

    fit <- aov(y ~ group, data = df)
    tbl <- anova(fit)

    ss_group <- tbl$`Sum Sq`[1]
    ss_resid <- tbl$`Sum Sq`[2]
    ss_total <- ss_group + ss_resid

    result$eta_squared <- ss_group / ss_total
    result$partial_eta_squared <- ss_group / (ss_group + ss_resid)
    result$ss_group <- ss_group
    result$ss_residual <- ss_resid
    result$ss_total <- ss_total

    # Also try effectsize package
    if (requireNamespace("effectsize", quietly = TRUE)) {
      eta <- effectsize::eta_squared(fit)
      result$effectsize_eta_sq <- eta$Eta2[1]
    }

    cat(" eta OK\n")

  } else {
    cat(" UNKNOWN TYPE:", meta$type, "\n")
    next
  }

  # Write results
  out_path <- file.path(script_dir, paste0("anova_", name, "_r_results.json"))
  write_json(result, out_path, auto_unbox = TRUE, pretty = TRUE, digits = 15)
  cat("  -> Written:", basename(out_path), "\n")
}

cat("\nAll done!\n")
