#!/usr/bin/env Rscript
#
# Run R survival analyses on fixtures generated by generate_survival_fixtures.py
#
# Usage:
#   Rscript tests/fixtures/run_r_survival_validation.R
#
# Reads surv_*_meta.json files, runs R's survival package, writes surv_*_r_results.json.

library(survival)
library(jsonlite)

# Determine script directory
args <- commandArgs(trailingOnly = FALSE)
file_arg <- grep("^--file=", args, value = TRUE)
if (length(file_arg) > 0) {
  script_dir <- normalizePath(dirname(sub("^--file=", "", file_arg)))
} else {
  script_dir <- normalizePath("tests/fixtures")
}

cat("Fixture directory:", script_dir, "\n\n")

# Find all surv_*_meta.json files
meta_files <- list.files(script_dir, pattern = "^surv_.*_meta\\.json$", full.names = TRUE)

if (length(meta_files) == 0) {
  cat("No surv_*_meta.json files found. Run generate_survival_fixtures.py first.\n")
  quit(status = 1)
}

cat("Found", length(meta_files), "fixture files\n\n")

for (mf in meta_files) {
  name <- sub("_meta\\.json$", "", basename(mf))
  name <- sub("^surv_", "", name)
  cat("Processing:", name, "...")

  meta <- fromJSON(mf)
  result <- list()

  if (meta$type == "kaplan_meier") {
    # ── Kaplan-Meier ──
    time <- as.numeric(meta$time)
    event <- as.numeric(meta$event)
    conf_level <- meta$conf_level
    conf_type <- meta$conf_type

    # Map conf_type to R's naming
    r_conf_type <- conf_type
    if (conf_type == "log-log") {
      r_conf_type <- "log-log"
    }

    fit <- survfit(Surv(time, event) ~ 1,
                   conf.int = conf_level,
                   conf.type = r_conf_type)
    s <- summary(fit)

    result$time <- as.numeric(s$time)
    result$n_risk <- as.numeric(s$n.risk)
    result$n_event <- as.numeric(s$n.event)
    result$n_censor <- as.numeric(s$n.censor)
    result$survival <- as.numeric(s$surv)
    result$se <- as.numeric(s$std.err)
    result$ci_lower <- as.numeric(s$lower)
    result$ci_upper <- as.numeric(s$upper)
    result$n <- fit$n
    result$events <- sum(event)
    result$median <- as.numeric(summary(fit)$table["median"])

  } else if (meta$type == "logrank") {
    # ── Log-rank test ──
    time <- as.numeric(meta$time)
    event <- as.numeric(meta$event)
    group <- as.factor(meta$group)
    rho <- meta$rho

    fit <- survdiff(Surv(time, event) ~ group, rho = rho)

    result$statistic <- as.numeric(fit$chisq)
    result$df <- length(levels(group)) - 1
    result$p_value <- as.numeric(1 - pchisq(fit$chisq, df = result$df))
    result$n_per_group <- as.numeric(fit$n)
    result$observed <- as.numeric(fit$obs)
    result$expected <- as.numeric(fit$exp)

  } else if (meta$type == "coxph") {
    # ── Cox PH ──
    time <- as.numeric(meta$time)
    event <- as.numeric(meta$event)
    # Handle X matrix — fromJSON may return matrix or list depending on shape
    if (is.matrix(meta$X)) {
      X <- meta$X
    } else if (is.list(meta$X)) {
      X <- as.matrix(do.call(rbind, lapply(meta$X, as.numeric)))
    } else {
      X <- as.matrix(as.numeric(meta$X))
    }
    ties_method <- meta$ties

    colnames(X) <- paste0("x", 1:ncol(X))
    df <- data.frame(time = time, event = event, X)
    covariate_names <- paste0("x", 1:ncol(X))

    formula_str <- paste("Surv(time, event) ~", paste(covariate_names, collapse = " + "))
    formula_obj <- as.formula(formula_str)

    fit <- coxph(formula_obj, data = df, ties = ties_method)
    s <- summary(fit)

    result$coefficients <- as.numeric(fit$coefficients)
    result$hazard_ratios <- as.numeric(exp(fit$coefficients))
    result$standard_errors <- as.numeric(sqrt(diag(fit$var)))
    result$z_statistics <- as.numeric(s$coefficients[, "z"])
    result$p_values <- as.numeric(s$coefficients[, "Pr(>|z|)"])
    result$loglik_null <- as.numeric(fit$loglik[1])
    result$loglik_model <- as.numeric(fit$loglik[2])
    result$concordance <- as.numeric(s$concordance[1])
    result$n_events <- fit$nevent
    result$n_observations <- fit$n
    result$n_iter <- fit$iter
  }

  # Write results
  out_path <- file.path(script_dir, paste0("surv_", name, "_r_results.json"))
  writeLines(toJSON(result, auto_unbox = TRUE, digits = 15, pretty = TRUE), out_path)
  cat(" done (", out_path, ")\n")
}

cat("\nAll fixtures processed.\n")
