"""
Tests for ARIMA information-criterion correctness (RIGOR R18, 4.6.4).

The seasonal-ARIMA IC bug counted the coefficients of the expanded
multiplicative AR/MA polynomials (k=15 for the airline model) instead
of the free estimated parameters (k=3), silently inflating aic/aicc/bic
and making ``auto_arima`` select inferior seasonal models. A second,
coupled bug estimated a mean/intercept for differenced models (R
``stats::arima`` drops it when d + D > 0), which acted as an implicit
drift term.

Reference values generated by
``tests/fixtures/generate_arima_ic_r_reference.R`` (R 4.5.2).
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest
from numpy.testing import assert_allclose

from pystatistics.core.exceptions import ValidationError
from pystatistics.timeseries import arima, auto_arima

FIXTURE = Path(__file__).parent.parent / "fixtures" / "arima_ic_r_reference.json"

# Optimizer noise between our L-BFGS-B fits and R's optim(BFGS) is
# ~1e-4..5e-2 log-likelihood units on these models; the IC bug this
# guards against was a +24 AIC error, so 0.2 is both tight and robust.
LOGLIK_ATOL = 0.1
IC_ATOL = 0.2


@pytest.fixture(scope="module")
def ref():
    with open(FIXTURE) as f:
        return json.load(f)


@pytest.fixture(scope="module")
def airpassengers(ref):
    return np.asarray(ref["series"]["airpassengers"], dtype=np.float64)


@pytest.fixture(scope="module")
def fits(ref, airpassengers):
    """Fit every reference model once; reused across tests."""
    out = {}
    for label, m in ref["models"].items():
        seasonal = tuple(m["seasonal"]) if m.get("seasonal") else None
        fit = arima(
            airpassengers,
            order=tuple(m["order"]),
            seasonal=seasonal,
            method="CSS-ML",
        )
        out[label] = (fit, m)
    return out


# =========================================================================
# Normal cases: self-consistency and R parity
# =========================================================================

class TestICSelfConsistency:
    """ARIMASolution must satisfy .aic == -2*loglik + 2*n_params etc."""

    def test_aic_uses_n_params(self, fits):
        for label, (fit, _) in fits.items():
            expected = -2.0 * fit.log_likelihood + 2.0 * fit.n_params
            assert_allclose(fit.aic, expected, atol=1e-8, err_msg=label)

    def test_aicc_uses_n_params(self, fits):
        for label, (fit, _) in fits.items():
            k, n = fit.n_params, fit.n_used
            expected = fit.aic + 2.0 * k * (k + 1.0) / (n - k - 1.0)
            assert_allclose(fit.aicc, expected, atol=1e-8, err_msg=label)

    def test_bic_uses_n_params(self, fits):
        for label, (fit, _) in fits.items():
            expected = (
                -2.0 * fit.log_likelihood + fit.n_params * np.log(fit.n_used)
            )
            assert_allclose(fit.bic, expected, atol=1e-8, err_msg=label)


class TestRParity:
    """Free parameter counts and IC values match R stats::arima."""

    def test_n_params_matches_r_free_k(self, fits):
        # Exact integer equality: the airline model must count k=3
        # (ma1, sma1, sigma2), not the 15 of the expanded polynomial.
        for label, (fit, m) in fits.items():
            assert fit.n_params == m["k"], (
                f"{label}: n_params={fit.n_params}, R free k={m['k']}"
            )

    def test_n_used_matches_r_nobs(self, fits):
        for label, (fit, m) in fits.items():
            assert fit.n_used == m["nobs"], label

    def test_loglik_matches_r(self, fits):
        for label, (fit, m) in fits.items():
            assert_allclose(
                fit.log_likelihood, m["loglik"], atol=LOGLIK_ATOL,
                err_msg=label,
            )

    @pytest.mark.parametrize("ic", ["aic", "aicc", "bic"])
    def test_ic_matches_r(self, fits, ic):
        for label, (fit, m) in fits.items():
            assert_allclose(
                getattr(fit, ic), m[ic], atol=IC_ATOL, err_msg=label,
            )


class TestMeanHandlingUnderDifferencing:
    """R parity: include_mean is ignored when d + D > 0."""

    def test_mean_dropped_when_d_positive(self, fits):
        fit, _ = fits["ns211"]
        assert fit.mean is None

    def test_mean_dropped_when_seasonal_D_positive(self, fits):
        fit, _ = fits["airline_011_011_12"]
        assert fit.mean is None

    def test_explicit_include_mean_still_dropped(self, airpassengers):
        fit = arima(airpassengers, order=(1, 1, 0), include_mean=True)
        assert fit.mean is None
        # and the count must not include it: ar1 + sigma2
        assert fit.n_params == 2

    def test_mean_kept_without_differencing(self, fits):
        fit, m = fits["ns101_with_mean"]
        assert fit.mean is not None
        assert fit.n_params == m["k"]  # ar1, ma1, intercept, sigma2 = 4


# =========================================================================
# Edge cases
# =========================================================================

class TestDegenerateModels:
    """(0,d,0) models: only sigma2 is estimated (k = 1)."""

    @pytest.mark.parametrize(
        "label", ["ns010_degenerate", "s010_010_12_degenerate"],
    )
    def test_k_is_one(self, fits, label):
        fit, m = fits[label]
        assert fit.n_params == 1 == m["k"]

    @pytest.mark.parametrize(
        "label", ["ns010_degenerate", "s010_010_12_degenerate"],
    )
    def test_aicc_correction(self, fits, label):
        # k=1: AICc = AIC + 2k(k+1)/(n-k-1) = AIC + 4/(n-2).
        fit, _ = fits[label]
        assert_allclose(
            fit.aicc, fit.aic + 4.0 / (fit.n_used - 2), atol=1e-10,
        )

    @pytest.mark.parametrize(
        "label", ["ns010_degenerate", "s010_010_12_degenerate"],
    )
    def test_matches_r(self, fits, label):
        fit, m = fits[label]
        assert_allclose(fit.aic, m["aic"], atol=IC_ATOL)
        assert_allclose(fit.aicc, m["aicc"], atol=IC_ATOL)


# =========================================================================
# auto_arima seasonal selection (the RIGOR R18 showstopper)
# =========================================================================

class TestAutoARIMASeasonalSelection:
    def test_matches_forecast_auto_arima(self, ref, airpassengers):
        """Default seasonal search must reproduce R's selection.

        Before the fix the inflated IC made auto_arima pick
        (2,1,2)(1,1,1)[12] — 7.5 AICc worse than R's choice by R's
        own (correct) accounting.
        """
        expected = ref["auto_arima_seasonal"]
        result = auto_arima(airpassengers, period=12, ic="aicc")
        assert result.best_order == tuple(expected["order"])
        assert result.best_seasonal == tuple(expected["seasonal"])
        assert_allclose(result.best_aic, expected["aicc"], atol=0.05)

    def test_search_visits_seasonal_orders(self, airpassengers):
        """The stepwise search must vary (P, Q), not pin them at (1, 1)."""
        result = auto_arima(airpassengers, period=12, ic="aicc")
        seasonal_orders = {
            s_order[:1] + s_order[2:3]
            for (_, s_order), _ in result.search_results
        }
        assert len(seasonal_orders) > 1

    def test_grid_search_covers_seasonal_grid(self, airpassengers):
        """stepwise=False iterates the full P/Q grid for seasonal models."""
        result = auto_arima(
            airpassengers, period=12, ic="aicc", stepwise=False,
            max_p=1, max_q=0, max_P=1, max_Q=1,
        )
        keys = {
            (order[0], order[2]) + s_order[:1] + s_order[2:3]
            for (order, s_order), _ in result.search_results
        }
        # 2 (p) * 1 (q) * 2 (P) * 2 (Q) distinct combinations
        assert len(keys) == 8
        assert result.best_seasonal is not None
        assert result.best_seasonal[3] == 12


class TestAutoARIMADifferencingChoice:
    def test_d_uses_kpss_like_forecast(self):
        """auto_arima's d comes from the KPSS test, as in R.

        forecast::auto.arima defaults to test='kpss'; the previous
        hardcoded test='adf' picked d=2 on WWWusage (over-differencing,
        R picks d=1) and d=0 on wineind (R: 1), sending the order
        search to the wrong model class entirely.
        """
        fixture = (
            Path(__file__).parent.parent
            / "fixtures" / "stationarity_r_reference.json"
        )
        with open(fixture) as f:
            www = np.asarray(
                json.load(f)["series"]["wwwusage"], dtype=np.float64,
            )
        result = auto_arima(www, period=1, ic="aicc")
        assert result.best_order[1] == 1


class TestWhittlePathMeanHandling:
    """The Whittle fast path shares the include_mean override and the
    free-parameter IC convention."""

    def test_mean_dropped_and_ic_consistent(self, airpassengers):
        fit = arima(airpassengers, order=(1, 1, 0), method="Whittle")
        assert fit.mean is None
        expected = -2.0 * fit.log_likelihood + 2.0 * fit.n_params
        assert_allclose(fit.aic, expected, atol=1e-8)
        assert fit.n_params == 2  # ar1 + sigma2


# =========================================================================
# Failure cases
# =========================================================================

class TestValidation:
    def test_negative_max_P_raises(self, airpassengers):
        with pytest.raises(ValidationError):
            auto_arima(airpassengers, period=12, max_P=-1)

    def test_negative_max_Q_raises(self, airpassengers):
        with pytest.raises(ValidationError):
            auto_arima(airpassengers, period=12, max_Q=-1)

    def test_negative_max_D_raises(self, airpassengers):
        with pytest.raises(ValidationError):
            auto_arima(airpassengers, period=12, max_D=-1)
