"""
R-parity tests for the ARIMA Kalman-path fixes (RIGOR R18 follow-up).

Three coupled defects, all confirmed against R 4.5.2:

1. The stationary initial covariance was solved by a linear fixed-point
   iteration with a 200-step budget and an absolute tolerance; a
   moderately persistent seasonal AR term (spectral radius ~0.94)
   failed the budget and silently fell back to the diffuse init,
   shifting the reported log-likelihood ~80 units below R on
   (1,1,1)(1,1,0)[12] models. Now solved by a doubling iteration.
2. Forecasts used the factored non-seasonal coefficients only (seasonal
   AR/MA dropped), seeded on CSS residuals (wrong near an MA unit
   root), and the SEs ignored differencing entirely (a random walk
   reported a flat se). Now forecast from the exact Kalman state, with
   the error covariance aggregated through the differencing operators.
3. vcov was computed over the expanded polynomial, so summary() read
   seasonal s.e. from structurally-zero lags. Now computed in the
   factored parameterization. sigma2 now reports the Kalman profile
   estimate for ML-family fits.

Reference values generated by
``tests/fixtures/generate_arima_kalman_r_reference.R`` (R 4.5.2).
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest
from numpy.testing import assert_allclose

from pystatistics.timeseries import arima
from pystatistics.timeseries._arima_forecast import forecast_arima
from pystatistics.timeseries._arima_kalman import _stationary_init

FIXTURE = Path(__file__).parent.parent / "fixtures" / "arima_kalman_r_reference.json"

# Optimizer noise bounds (measured deltas are ~1e-3; the defects being
# guarded against were 80 loglik units, 1.4-5.4 forecast units, and a
# 4.7x s.e. error).
LOGLIK_ATOL = 0.05
FC_MEAN_ATOL = 0.05
FC_SE_ATOL = 0.02
SE_ATOL = 2e-3


@pytest.fixture(scope="module")
def ref():
    with open(FIXTURE) as f:
        return json.load(f)


_SERIES_KEY = {
    "logap": "log_airpassengers",
    "nottem": "nottem",
    "co2": "co2",
}


@pytest.fixture(scope="module")
def fits(ref):
    """Fit every reference model once; reused across tests."""
    out = {}
    for label, m in ref["fits"].items():
        series_key = next(
            (v for k, v in _SERIES_KEY.items() if label.startswith(k)),
            "airpassengers",
        )
        x = np.asarray(ref["series"][series_key], dtype=np.float64)
        seasonal = tuple(m["seasonal"]) if m.get("seasonal") else None
        fit = arima(x, order=tuple(m["order"]), seasonal=seasonal,
                    method="CSS-ML")
        out[label] = (fit, m, x)
    return out


# =========================================================================
# Defect 1: seasonal-AR exact-ML likelihood
# =========================================================================

class TestSeasonalARLikelihood:
    """(1,1,1)(1,1,0)[12] fits must reproduce R's log-likelihood.

    Before the doubling-init fix these reported ~80 units below R.
    """

    @pytest.mark.parametrize("label", ["logap_111_110", "nottem_111_110"])
    def test_loglik_matches_r(self, fits, label):
        fit, m, _ = fits[label]
        assert_allclose(fit.log_likelihood, m["loglik"], atol=LOGLIK_ATOL)

    @pytest.mark.parametrize("label", ["logap_111_110", "nottem_111_110"])
    def test_coefficients_match_r(self, fits, label):
        fit, m, _ = fits[label]
        assert_allclose(fit.ar[0], m["coef"]["ar1"], atol=5e-3)
        assert_allclose(fit.ma[0], m["coef"]["ma1"], atol=5e-3)
        assert_allclose(fit.seasonal_ar[0], m["coef"]["sar1"], atol=5e-3)

    @pytest.mark.parametrize("label", ["logap_111_110", "nottem_111_110"])
    def test_aic_matches_r(self, fits, label):
        fit, m, _ = fits[label]
        assert_allclose(fit.aic, m["aic"], atol=2 * LOGLIK_ATOL)
        assert_allclose(fit.aicc, m["aicc"], atol=2 * LOGLIK_ATOL)


class TestStationaryInit:
    """The doubling iteration itself: normal, edge, failure."""

    def test_converges_for_persistent_seasonal_ar(self):
        # The exact failure case: expanded (1 - sar B^12) polynomial,
        # spectral radius ~0.94 — the old fixed-point gave ok=False.
        phi = np.zeros(13)
        phi[11] = -0.4731  # sar1 at lag 12 (expanded, 0-indexed lag 12)
        phi[12] = 0.0547 * 0.4731
        phi[0] = 0.0547
        R_vec = np.zeros(13)
        R_vec[0] = 1.0
        R_vec[1] = -0.4886
        P, ok = _stationary_init(phi, R_vec)
        assert ok
        # P must satisfy the Lyapunov equation P = T P T' + RR'.
        T = np.zeros((13, 13))
        T[:, 0] = phi
        for i in range(12):
            T[i, i + 1] = 1.0
        residual = T @ P @ T.T + np.outer(R_vec, R_vec) - P
        assert np.abs(residual).max() < 1e-10

    def test_agrees_with_scipy_lyapunov(self):
        from scipy.linalg import solve_discrete_lyapunov

        phi = np.array([0.5, -0.2, 0.05])
        R_vec = np.array([1.0, 0.3, 0.0])
        P, ok = _stationary_init(phi, R_vec)
        assert ok
        T = np.zeros((3, 3))
        T[:, 0] = phi
        T[0, 1] = T[1, 2] = 1.0
        P_ref = solve_discrete_lyapunov(T, np.outer(R_vec, R_vec))
        assert_allclose(P, P_ref, atol=1e-10)

    def test_white_noise_state(self):
        P, ok = _stationary_init(np.zeros(1), np.ones(1))
        assert ok
        assert_allclose(P, [[1.0]], atol=1e-14)

    def test_nonstationary_signals_failure(self):
        # Explosive AR: the doubling must NOT report success.
        P, ok = _stationary_init(np.array([1.5]), np.ones(1))
        assert not ok


# =========================================================================
# Defect 2: forecast parity with R predict.Arima
# =========================================================================

FORECAST_LABELS = [
    "airline", "s211_010", "ns211", "ns010",
    "logap_111_110", "nottem_111_110",
    # d >= 2 / D >= 2: guard the _undifference integration order (the
    # (1,2,1) mean was off by four orders of magnitude at h=12).
    "d2_121", "d2_020", "D2_011_021",
]


class TestForecastRParity:
    @pytest.mark.parametrize("label", FORECAST_LABELS)
    def test_mean_matches_r(self, fits, label):
        fit, m, x = fits[label]
        fc = forecast_arima(fit, x, h=12)
        # Scale tolerance to the series (log-scale models are ~5.5).
        scale = max(1.0, float(np.mean(np.abs(x))) / 450.0)
        assert_allclose(
            fc.mean, m["fc_mean"], atol=FC_MEAN_ATOL * scale, err_msg=label,
        )

    @pytest.mark.parametrize("label", FORECAST_LABELS)
    def test_se_matches_r(self, fits, label):
        fit, m, x = fits[label]
        fc = forecast_arima(fit, x, h=12)
        # Relative: guards both the flat-se defect (rw: 3.5x off at
        # h=12) and the sigma2 defect (1.4% off).
        assert_allclose(
            fc.se, m["fc_se"], rtol=5e-3, err_msg=label,
        )

    def test_forecast_failure_is_loud(self, fits):
        # kalman_arma_forecast must raise, not return garbage, when the
        # filter fails at pathological parameters (non-finite AR poisons
        # the covariance propagation; the explosive-but-finite case is
        # self-stabilizing because the measurement is exact).
        from pystatistics.core.exceptions import ValidationError
        from pystatistics.timeseries._arima_kalman import (
            kalman_arma_forecast,
        )

        with pytest.raises(ValidationError):
            kalman_arma_forecast(
                np.ones(50), np.array([np.nan]), np.array([]), 5,
            )

    def test_random_walk_se_is_analytic(self, fits):
        # (0,1,0): se(h) = sigma * sqrt(h) exactly.
        fit, _, x = fits["ns010"]
        fc = forecast_arima(fit, x, h=8)
        expected = np.sqrt(fit.sigma2 * np.arange(1, 9))
        assert_allclose(fc.se, expected, rtol=1e-10)

    def test_se_increases_for_integrated_models(self, fits):
        fit, _, x = fits["ns211"]
        fc = forecast_arima(fit, x, h=12)
        assert np.all(np.diff(fc.se) > 0)


# =========================================================================
# Defect 3: sigma2 and coefficient standard errors
# =========================================================================

class TestConvergedFlag:
    def test_ml_success_overrides_css_failure(self, fits):
        # co2 (2,1,1): the CSS warm-start aborts on a NaN objective but
        # the ML refinement converges to R's optimum; the fit must not
        # raise and must match R.
        fit, m, _ = fits["co2_211"]
        assert fit.converged
        assert_allclose(fit.log_likelihood, m["loglik"], atol=LOGLIK_ATOL)


class TestSigma2AndSE:
    @pytest.mark.parametrize(
        "label", ["airline", "s211_010", "ns211", "logap_111_110"],
    )
    def test_sigma2_is_kalman_profile(self, fits, label):
        # The CSS-residual SSE/n overstated sigma2 by 2.9% on the
        # near-unit-MA model; R's profile estimate is the reference.
        fit, m, _ = fits[label]
        assert_allclose(fit.sigma2, m["sigma2"], rtol=5e-3, err_msg=label)

    @pytest.mark.parametrize("label", ["airline", "logap_111_110"])
    def test_seasonal_se_matches_r(self, fits, label):
        # vcov now lives in the factored parameterization: the s.e.
        # printed for sar/sma must be R's (airline sma1 was 4.7x off).
        fit, m, _ = fits[label]
        se = np.sqrt(np.abs(np.diag(fit.vcov)))
        names = []
        for i in range(len(fit.ar)):
            names.append(f"ar{i + 1}")
        for i in range(len(fit.ma)):
            names.append(f"ma{i + 1}")
        for i in range(len(fit.seasonal_ar)):
            names.append(f"sar{i + 1}")
        for i in range(len(fit.seasonal_ma)):
            names.append(f"sma{i + 1}")
        for idx, name in enumerate(names):
            assert_allclose(
                se[idx], m["se"][name], atol=SE_ATOL,
                err_msg=f"{label}:{name}",
            )

    def test_vcov_dimension_matches_coefficients(self, fits):
        # For seasonal fits vcov must be (p+q+P+Q) square, not the
        # expanded-polynomial size.
        fit, _, _ = fits["airline"]
        n_coef = (len(fit.ar) + len(fit.ma)
                  + len(fit.seasonal_ar) + len(fit.seasonal_ma))
        assert fit.vcov.shape == (n_coef, n_coef)


# =========================================================================
# auto_arima near-unit-root candidate veto (forecast::auto.arima parity)
# =========================================================================

class TestNearUnitRootVeto:
    def test_boundary_ma_root_is_vetoed(self, fits):
        # nottem (1,1,1)(1,1,0)[12] fits with ma1 ~ -1.0 (root modulus
        # ~1.00001 < 1.01): forecast's myarima would set ic = Inf.
        from pystatistics.timeseries._arima_order import _has_near_unit_roots

        fit, _, _ = fits["nottem_111_110"]
        assert abs(fit.ma[0]) > 0.98  # precondition: boundary fit
        assert _has_near_unit_roots(fit)

    def test_interior_roots_survive(self, fits):
        # (2,1,1)(0,1,0)[12] has min MA root modulus ~1.018 > 1.01 —
        # R's own auto.arima pick, must NOT be vetoed.
        from pystatistics.timeseries._arima_order import _has_near_unit_roots

        fit, _, _ = fits["s211_010"]
        assert not _has_near_unit_roots(fit)

    def test_pure_differencing_survives(self, fits):
        # No AR/MA coefficients at all: nothing to veto.
        from pystatistics.timeseries._arima_order import _has_near_unit_roots

        fit, _, _ = fits["ns010"]
        assert not _has_near_unit_roots(fit)
