"""
Tests for the RIGOR R18 stationarity-test fixes (4.6.4):

- adf_test defaults to regression='ct' (tseries::adf.test always uses
  constant + trend) and its statistic reproduces tseries exactly.
- ADF p-values use the MacKinnon (1994) surface and match statsmodels
  ``adfuller`` across nc/c/ct and the full p range — the old
  interpolation returned p=0.44 for a near-unit-root series where the
  correct value is ~0.92.
- kpss_test's default bandwidth follows tseries's lshort=TRUE rule
  trunc(4*(n/100)^(1/4)); at that (matched) bandwidth the statistic
  and interpolated p-value reproduce tseries::kpss.test.

Reference values generated by
``tests/fixtures/generate_stationarity_r_reference.R`` (R 4.5.2,
tseries 0.10-58) and
``tests/fixtures/generate_adf_statsmodels_reference.py``
(statsmodels 0.14.6).
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest
from numpy.testing import assert_allclose

from pystatistics.core.exceptions import ValidationError
from pystatistics.timeseries import adf_test, kpss_test, ndiffs
from pystatistics.timeseries._adf_mackinnon import (
    adf_critical_values,
    adf_pvalue,
)

FIXTURES = Path(__file__).parent.parent / "fixtures"


@pytest.fixture(scope="module")
def r_ref():
    with open(FIXTURES / "stationarity_r_reference.json") as f:
        return json.load(f)


@pytest.fixture(scope="module")
def sm_ref():
    with open(FIXTURES / "adf_statsmodels_reference.json") as f:
        return json.load(f)


@pytest.fixture(scope="module")
def series(r_ref):
    return {
        name: np.asarray(vals, dtype=np.float64)
        for name, vals in r_ref["series"].items()
    }


# =========================================================================
# ADF: default regression and tseries statistic parity
# =========================================================================

class TestADFDefault:
    def test_default_regression_is_ct(self, series):
        result = adf_test(series["near_unit_root"])
        assert result.info["regression"] == "ct"

    def test_default_statistic_matches_tseries(self, series, r_ref):
        # tseries::adf.test always uses constant + trend; with the new
        # default the statistic must reproduce it exactly.
        for name, x in series.items():
            expected = r_ref["reference"][name]
            result = adf_test(x)
            assert_allclose(
                result.statistic, expected["adf_stat"], atol=1e-6,
                err_msg=name,
            )
            assert result.n_lags == expected["adf_lag"], name

    def test_all_regressions_still_available(self, series):
        x = series["stationary_ar1"]
        for regression in ("nc", "c", "ct"):
            result = adf_test(x, regression=regression)
            assert result.info["regression"] == regression


# =========================================================================
# ADF: MacKinnon p-values vs statsmodels (full range, all regressions)
# =========================================================================

class TestADFPvalueMacKinnon:
    def test_matches_statsmodels_adfuller(self, series, sm_ref):
        for case in sm_ref["cases"]:
            x = series[case["series"]]
            result = adf_test(
                x, regression=case["regression"], n_lags=case["n_lags"],
            )
            assert_allclose(
                result.statistic, case["statistic"], atol=1e-8,
                err_msg=str(case),
            )
            assert_allclose(
                result.p_value, case["pvalue"], atol=1e-8,
                err_msg=str(case),
            )

    def test_near_unit_root_upper_tail(self):
        # The RIGOR R18 defect: statistic -1.1426 (ct) reported p=0.44;
        # tseries gives 0.9144, statsmodels (MacKinnon) 0.9216.
        p = adf_pvalue(-1.1426, "ct")
        assert p > 0.9
        assert_allclose(p, 0.9216, atol=5e-4)

    def test_deep_reject_lower_tail_resolves(self, series):
        # tseries caps at p=0.01; the MacKinnon surface keeps resolving.
        result = adf_test(series["log_lynx"], regression="ct")
        assert 0.0 <= result.p_value < 0.01

    def test_monotone_in_statistic(self):
        for regression in ("nc", "c", "ct"):
            grid = np.arange(-8.0, 0.51, 0.05)
            pvals = [adf_pvalue(float(t), regression) for t in grid]
            assert all(a <= b for a, b in zip(pvals, pvals[1:])), regression

    def test_saturation(self):
        assert adf_pvalue(-30.0, "ct") == 0.0
        assert adf_pvalue(1.0, "ct") == 1.0
        assert adf_pvalue(3.0, "c") == 1.0


class TestADFCriticalValues:
    def test_levels_ordered(self):
        cv = adf_critical_values("ct", 100)
        assert cv["1%"] < cv["5%"] < cv["10%"] < 0.0

    def test_asymptote(self):
        # MacKinnon (2010) asymptotic 1% value for 'ct' is -3.95877.
        cv = adf_critical_values("ct", 10**9)
        assert_allclose(cv["1%"], -3.95877, atol=1e-4)

    def test_invalid_regression_raises(self):
        with pytest.raises(ValidationError):
            adf_pvalue(-2.0, "ctt")
        with pytest.raises(ValidationError):
            adf_critical_values("bogus", 100)

    def test_nonpositive_nobs_raises(self):
        with pytest.raises(ValidationError):
            adf_critical_values("ct", 0)


# =========================================================================
# KPSS: tseries bandwidth rule and parity
# =========================================================================

class TestKPSSBandwidth:
    @pytest.mark.parametrize(
        "n,expected", [(50, 3), (100, 4), (200, 4), (400, 5), (1000, 7)],
    )
    def test_lshort_true_rule(self, n, expected, rng_series):
        assert kpss_test(rng_series(n)).n_lags == expected

    @pytest.mark.parametrize(
        "n,expected", [(100, 12), (200, 14), (400, 16)],
    )
    def test_lshort_false_rule(self, n, expected, rng_series):
        assert kpss_test(rng_series(n), lshort=False).n_lags == expected

    def test_explicit_n_lags_overrides_lshort(self, rng_series):
        x = rng_series(200)
        assert kpss_test(x, n_lags=7, lshort=False).n_lags == 7
        assert kpss_test(x, n_lags=0).n_lags == 0

    def test_lshort_must_be_bool(self, rng_series):
        with pytest.raises(ValidationError):
            kpss_test(rng_series(100), lshort="yes")


@pytest.fixture(scope="module")
def rng_series():
    def _make(n: int):
        return np.random.default_rng(7).normal(size=n)

    return _make


class TestKPSSDegenerateInput:
    def test_constant_series_raises(self):
        # 0/0 statistic: any returned value would be rounding noise.
        with pytest.raises(ValidationError):
            kpss_test(np.full(50, 5.0))

    def test_exactly_linear_series_raises_under_ct(self):
        with pytest.raises(ValidationError):
            kpss_test(np.arange(50, dtype=np.float64), regression="ct")

    def test_exactly_linear_series_ok_under_c(self):
        # A pure trend has real level-regression residuals; must work.
        result = kpss_test(np.arange(50, dtype=np.float64), regression="c")
        assert np.isfinite(result.statistic)


class TestNdiffsForecastParity:
    """ndiffs (default KPSS path) must match forecast::ndiffs.

    Guards the bandwidth pin: forecast::ndiffs uses
    use.lag = trunc(3*sqrt(n)/13), NOT kpss_test's tseries-style
    lshort default. WWWusage is the borderline case that separates
    the two (2 lags -> d=1, 4 lags -> d=0).
    """

    def test_matches_forecast_ndiffs(self, series, r_ref):
        for name, expected in r_ref["ndiffs_kpss"].items():
            assert ndiffs(series[name]) == expected, name


class TestKPSSTseriesParity:
    def test_level(self, series, r_ref):
        for name, x in series.items():
            expected = r_ref["reference"][name]
            result = kpss_test(x, regression="c")
            assert result.n_lags == expected["kpss_level_lag"], name
            assert_allclose(
                result.statistic, expected["kpss_level_stat"], atol=1e-8,
                err_msg=name,
            )
            assert_allclose(
                result.p_value, expected["kpss_level_p"], atol=1e-6,
                err_msg=name,
            )

    def test_trend(self, series, r_ref):
        for name, x in series.items():
            expected = r_ref["reference"][name]
            result = kpss_test(x, regression="ct")
            assert result.n_lags == expected["kpss_trend_lag"], name
            assert_allclose(
                result.statistic, expected["kpss_trend_stat"], atol=1e-8,
                err_msg=name,
            )
            assert_allclose(
                result.p_value, expected["kpss_trend_p"], atol=1e-6,
                err_msg=name,
            )
