"""
Tests for regression with ARIMA errors: ``xreg``, drift, and ``fixed=``
(VA-4 / VA-4b).

Validates ``arima(..., xreg=)`` / ``include_drift`` / ``fixed`` and
``forecast_arima(..., newxreg=)`` against R ``stats::arima`` +
``predict.Arima`` — the exact-ML reference pystatistics targets (MLE
``sigma2``; ``predict.Arima`` prediction SEs use that ``sigma2``). Covers
the RIGOR R10 hard cases: xreg under differencing, near-collinear xreg,
all-but-one fixed, drift under ``d = 1``, and seasonal + xreg.

Reference values generated by
``tests/fixtures/generate_arima_xreg_r_reference.R`` (R 4.5.2).
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest
from numpy.testing import assert_allclose

from pystatistics.core.exceptions import ValidationError
from pystatistics.timeseries import arima, auto_arima, forecast_arima

FIXTURE = Path(__file__).parent.parent / "fixtures" / "arima_xreg_r_reference.json"

# L-BFGS-B vs R optim(BFGS) optimizer noise on these fits is ~1e-5..1e-3
# on coefficients; these tolerances are tight enough to catch a real
# specification error while robust to optimizer differences.
COEF_ATOL = 8e-3
LOGLIK_ATOL = 0.05
IC_ATOL = 0.1
SE_ATOL = 5e-3
FC_ATOL = 5e-3


@pytest.fixture(scope="module")
def ref():
    with open(FIXTURE) as f:
        return json.load(f)


@pytest.fixture(scope="module")
def series(ref):
    return {k: np.asarray(v, dtype=np.float64) for k, v in ref["series"].items()}


# ---------------------------------------------------------------------------
# Per-model fit configuration: how to invoke pystatistics for each R model.
# ---------------------------------------------------------------------------

def _fit_model(label: str, s: dict):
    """Reproduce the R reference fit for ``label`` with pystatistics."""
    x1, x2 = s["x1"], s["x2"]
    if label == "A":
        return arima(s["yA"], order=(1, 0, 0), xreg=np.column_stack([x1, x2]))
    if label == "MA":
        return arima(s["yMA"], order=(1, 0, 1), xreg=x1)
    if label == "D":  # drift as an explicit trend
        return arima(s["yD"], order=(0, 1, 1), include_drift=True)
    if label == "Xd":
        return arima(s["yXd"], order=(2, 1, 0), xreg=x1)
    if label == "FixedMA":
        return arima(s["e_arma"], order=(1, 0, 1), fixed={"ma1": 0})
    if label == "FixedAR":
        return arima(s["e_arma"], order=(2, 0, 0), fixed={"ar2": 0.2})
    if label == "Collinear":
        return arima(s["yC"], order=(1, 0, 0),
                     xreg=np.column_stack([s["xc1"], s["xc2"]]))
    if label == "SeasonalXreg":
        return arima(s["yS"], order=(0, 0, 0), seasonal=(1, 0, 0, 4), xreg=x1)
    raise KeyError(label)


def _py_coef_vector(fit) -> np.ndarray:
    """Full coefficient vector in R's coef() order: ar, ma, sar, sma, reg."""
    return np.concatenate([
        fit.ar, fit.ma, fit.seasonal_ar, fit.seasonal_ma, fit.xreg_coef,
    ])


ALL_LABELS = ["A", "MA", "D", "Xd", "FixedMA", "FixedAR", "Collinear",
              "SeasonalXreg"]
FIXED_LABELS = {"FixedMA", "FixedAR"}


@pytest.fixture(scope="module")
def fits(ref, series):
    return {label: _fit_model(label, series) for label in ALL_LABELS}


# ---------------------------------------------------------------------------
# Estimator-invariant parity (coef / loglik / AIC / sigma2 / SE)
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("label", ALL_LABELS)
def test_coefficients_match_r(label, ref, fits):
    m = ref["models"][label]
    py = _py_coef_vector(fits[label])
    r = np.asarray(m["coef"], dtype=np.float64)
    assert py.shape == r.shape, (label, m["coef_names"])
    assert_allclose(py, r, atol=COEF_ATOL, err_msg=f"{label}: {m['coef_names']}")


@pytest.mark.parametrize("label", ALL_LABELS)
def test_loglik_aic_sigma2_match_r(label, ref, fits):
    m = ref["models"][label]
    fit = fits[label]
    assert_allclose(fit.log_likelihood, m["loglik"], atol=LOGLIK_ATOL)
    assert_allclose(fit.aic, m["aic"], atol=IC_ATOL)
    assert_allclose(fit.sigma2, m["sigma2"], rtol=5e-3)


@pytest.mark.parametrize("label", [l for l in ALL_LABELS if l not in FIXED_LABELS])
def test_standard_errors_match_r(label, ref, fits):
    """SE parity for free parameters (R var.coef excludes fixed params)."""
    m = ref["models"][label]
    se = np.sqrt(np.abs(np.diag(fits[label].vcov)))
    assert_allclose(se, np.asarray(m["se"]), atol=SE_ATOL,
                    err_msg=f"{label}: {m['coef_names']}")


@pytest.mark.parametrize("label", sorted(FIXED_LABELS))
def test_fixed_coefficient_pinned_exactly(label, ref, fits):
    """A fixed coefficient is held EXACTLY at its value (zero variance)."""
    m = ref["models"][label]
    py = _py_coef_vector(fits[label])
    r = np.asarray(m["coef"], dtype=np.float64)
    fixed_val = 0.0 if label == "FixedMA" else 0.2
    # Locate the fixed entry (ma1 for FixedMA, ar2 for FixedAR).
    idx = m["coef_names"].index("ma1" if label == "FixedMA" else "ar2")
    assert py[idx] == pytest.approx(fixed_val, abs=1e-12)
    # Its vcov row/column is exactly zero.
    assert np.all(fits[label].vcov[idx, :] == 0.0)
    assert np.all(fits[label].vcov[:, idx] == 0.0)
    # The free coefficients still match R.
    assert_allclose(py, r, atol=COEF_ATOL)


# ---------------------------------------------------------------------------
# Forecasting with newxreg / drift continuation
# ---------------------------------------------------------------------------

def test_forecast_xreg_matches_predict_arima(ref, series, fits):
    """Point + SE forecasts with newxreg match predict.Arima (Case A)."""
    m = ref["models"]["A"]
    fit = fits["A"]
    newx = np.asarray(series["newxA"], dtype=np.float64).reshape(6, 2)
    fc = forecast_arima(fit, series["yA"], h=m["h"], levels=[95], newxreg=newx)
    assert_allclose(fc.mean, np.asarray(m["fc"]), atol=FC_ATOL)
    z = 1.959963984540054
    py_se = (fc.upper[95] - fc.mean) / z
    assert_allclose(py_se, np.asarray(m["fcse"]), atol=FC_ATOL)


def test_forecast_drift_continues_linearly(ref, series, fits):
    """Drift forecasts continue the trend and need no newxreg (Case D)."""
    m = ref["models"]["D"]
    fc = forecast_arima(fits["D"], series["yD"], h=m["h"], levels=[95])
    assert_allclose(fc.mean, np.asarray(m["fc"]), atol=FC_ATOL)


def test_forecast_xreg_under_differencing(ref, series, fits):
    """Forecasts for an xreg model with d=1 (Case Xd)."""
    m = ref["models"]["Xd"]
    newx = np.asarray(series["newxXd"], dtype=np.float64).reshape(6, 1)
    fc = forecast_arima(fits["Xd"], series["yXd"], h=m["h"], levels=[95],
                        newxreg=newx)
    assert_allclose(fc.mean, np.asarray(m["fc"]), atol=1e-2)


# ---------------------------------------------------------------------------
# auto_arima drift selection
# ---------------------------------------------------------------------------

def _drift_series():
    """Deterministic random walk with a strong drift (reliably d=1)."""
    rng = np.random.default_rng(0)
    n = 100
    return np.cumsum(np.concatenate([[10.0], 0.8 + 0.5 * rng.standard_normal(n - 1)]))


def test_auto_arima_selects_drift():
    """auto_arima selects a drift model for a random walk with drift."""
    res = auto_arima(_drift_series(), period=1, stepwise=True)
    assert res.best_model.include_drift
    assert "drift" in res.best_model.xreg_names
    # The drift coefficient is near the true 0.8 trend.
    drift = res.best_model.xreg_coef[res.best_model.xreg_names.index("drift")]
    assert 0.4 < drift < 1.2


def test_auto_arima_allowdrift_false_disables():
    """allowdrift=False never selects a drift term."""
    res = auto_arima(_drift_series(), period=1, stepwise=True, allowdrift=False)
    assert not res.best_model.include_drift


# ---------------------------------------------------------------------------
# summary() surfaces regression coefficients
# ---------------------------------------------------------------------------

def test_summary_includes_regression_coefs(fits):
    text = fits["A"].summary()
    for name in ("ar1", "intercept", "xreg1", "xreg2"):
        assert name in text


# ---------------------------------------------------------------------------
# Edge / failure cases (Rule 1: fail loud)
# ---------------------------------------------------------------------------

def test_xreg_wrong_length_raises(series):
    with pytest.raises(ValidationError, match="one row per observation"):
        arima(series["yA"], order=(1, 0, 0), xreg=series["x1"][:-3])


def test_fixed_unknown_name_raises(series):
    with pytest.raises(ValidationError, match="unknown coefficient name"):
        arima(series["e_arma"], order=(1, 0, 1), fixed={"ar9": 0})


def test_all_fixed_raises(series):
    with pytest.raises(ValidationError, match="nothing to"):
        arima(series["e_arma"], order=(1, 0, 0),
              fixed={"ar1": 0.5, "intercept": 0.0})


def test_drift_with_double_differencing_raises(series):
    with pytest.raises(ValidationError, match="drift regressor vanishes"):
        arima(series["yD"], order=(0, 2, 1), include_drift=True)


def test_newxreg_required_when_missing(series, fits):
    with pytest.raises(ValidationError, match="future regressor values"):
        forecast_arima(fits["A"], series["yA"], h=6)


def test_newxreg_wrong_shape_raises(series, fits):
    with pytest.raises(ValidationError, match="expected shape"):
        forecast_arima(fits["A"], series["yA"], h=6,
                       newxreg=np.zeros((6, 1)))


def test_whittle_with_xreg_raises(series):
    with pytest.raises(ValidationError, match="not supported with method='Whittle'"):
        arima(series["yA"], order=(1, 0, 0), xreg=series["x1"], method="Whittle")


def test_init_with_xreg_raises(series):
    with pytest.raises(ValidationError, match="not supported together with"):
        arima(series["yA"], order=(1, 0, 0), xreg=series["x1"],
              init=[0.5, 0.0, 0.0, 0.0])


def test_positional_fixed_vector_accepted(series):
    """R-style positional nan-vector is accepted alongside the dict form."""
    fit_dict = arima(series["e_arma"], order=(1, 0, 1), fixed={"ma1": 0})
    fit_vec = arima(series["e_arma"], order=(1, 0, 1),
                    fixed=[np.nan, 0.0, np.nan])
    assert_allclose(fit_dict.ar, fit_vec.ar, atol=1e-10)
    assert_allclose(fit_dict.ma, fit_vec.ma, atol=1e-10)


def test_xreg_forecast_roundtrip_no_regression_unaffected(series):
    """A plain (no-xreg) fit still forecasts identically (no regression path)."""
    fit = arima(series["yA"], order=(1, 0, 0))
    fc = forecast_arima(fit, series["yA"], h=5)
    assert fc.mean.shape == (5,)
    assert len(fit.xreg_coef) == 0
