"""
STL parity tests against R stats::stl reference fixtures.

Every case in ``tests/fixtures/stl_r_reference.json`` was generated by
R 4.5.2's ``stats::stl`` with the exact parameters recorded in the
fixture; the tests feed the same parameters to ``pystatistics`` and
require the seasonal/trend/remainder components (and, for robust cases,
the robustness weights) to agree to float-noise tolerance.  The observed
worst-case difference across the suite is ~3e-11 (accumulated float
noise over the iterated smoothing passes); the asserted tolerance of
1e-9 absolute is a conservative ceiling, far below any statistically
meaningful scale.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest

from pystatistics.timeseries import stl

FIXTURE = Path(__file__).parent.parent / "fixtures" / "stl_r_reference.json"

# Absolute tolerance for component parity (see module docstring).
ATOL = 1e-9

# R stl() argument names -> pystatistics stl() keyword names.
_ARG_MAP = {
    "s.window": "seasonal_window",
    "s.degree": "seasonal_degree",
    "t.window": "trend_window",
    "t.degree": "trend_degree",
    "l.window": "lowpass_window",
    "l.degree": "lowpass_degree",
    "s.jump": "seasonal_jump",
    "t.jump": "trend_jump",
    "l.jump": "lowpass_jump",
    "robust": "robust",
    "inner": "n_inner",
    "outer": "n_outer",
}


def _load_cases() -> dict:
    with open(FIXTURE) as fh:
        return json.load(fh)


_CASES = _load_cases()


def _kwargs(case: dict) -> dict:
    return {_ARG_MAP[k]: v for k, v in case["args"].items()}


@pytest.mark.parametrize("name", sorted(_CASES))
def test_components_match_r(name):
    """seasonal/trend/remainder match R stats::stl for identical params."""
    case = _CASES[name]
    sol = stl(np.asarray(case["x"], dtype=float), case["period"],
              **_kwargs(case))
    np.testing.assert_allclose(
        sol.seasonal, case["seasonal"], atol=ATOL, rtol=0.0,
        err_msg=f"{name}: seasonal mismatch vs R",
    )
    np.testing.assert_allclose(
        sol.trend, case["trend"], atol=ATOL, rtol=0.0,
        err_msg=f"{name}: trend mismatch vs R",
    )
    np.testing.assert_allclose(
        sol.residual, case["remainder"], atol=ATOL, rtol=0.0,
        err_msg=f"{name}: remainder mismatch vs R",
    )


@pytest.mark.parametrize("name", sorted(_CASES))
def test_robustness_weights_match_r(name):
    """Final robustness weights match R (ones for non-robust runs)."""
    case = _CASES[name]
    sol = stl(np.asarray(case["x"], dtype=float), case["period"],
              **_kwargs(case))
    np.testing.assert_allclose(
        sol.info["robustness_weights"], case["weights"], atol=ATOL, rtol=0.0,
        err_msg=f"{name}: robustness weights mismatch vs R",
    )


@pytest.mark.parametrize("name", sorted(_CASES))
def test_resolved_parameters_match_r(name):
    """Windows/degrees/jumps resolved from defaults equal R's."""
    case = _CASES[name]
    sol = stl(np.asarray(case["x"], dtype=float), case["period"],
              **_kwargs(case))
    info = sol.info
    assert info["windows"] == {
        "seasonal": case["win"]["s"],
        "trend": case["win"]["t"],
        "lowpass": case["win"]["l"],
    }, f"{name}: window resolution differs from R"
    assert info["degrees"] == {
        "seasonal": case["deg"]["s"],
        "trend": case["deg"]["t"],
        "lowpass": case["deg"]["l"],
    }, f"{name}: degree resolution differs from R"
    assert info["jumps"] == {
        "seasonal": case["jump"]["s"],
        "trend": case["jump"]["t"],
        "lowpass": case["jump"]["l"],
    }, f"{name}: jump resolution differs from R"
    assert info["n_inner"] == case["inner"]
    assert info["n_outer"] == case["outer"]


def test_co2_headline_decomposition():
    """The showstopper case: stl(co2, 12) must track R, not the old bug.

    The pre-4.6.2 implementation returned a seasonal range of ~82.8 and a
    trend that *decreased* at the end of a monotonically rising series.
    """
    case = _CASES["co2_periodic"]
    sol = stl(np.asarray(case["x"], dtype=float), 12)  # all defaults
    seasonal_range = float(np.ptp(sol.seasonal))
    assert abs(seasonal_range - 6.174) < 0.01
    np.testing.assert_allclose(
        sol.trend[:3], [315.195, 315.302, 315.409], atol=1e-3)
    np.testing.assert_allclose(
        sol.trend[-3:], [364.223, 364.343, 364.467], atol=1e-3)
    # Trend must be increasing overall (co2 rises 315 -> 364).
    assert sol.trend[-1] > sol.trend[0] + 45.0


def test_identity_exact():
    """seasonal + trend + residual == observed to machine precision."""
    case = _CASES["airpassengers_s11"]
    x = np.asarray(case["x"], dtype=float)
    sol = stl(x, case["period"], **_kwargs(case))
    np.testing.assert_allclose(
        sol.seasonal + sol.trend + sol.residual, x, atol=1e-12, rtol=0.0)


def test_periodic_seasonal_is_exactly_periodic():
    """seasonal_window='periodic' yields an exactly repeating seasonal."""
    case = _CASES["co2_periodic"]
    sol = stl(np.asarray(case["x"], dtype=float), 12)
    period = 12
    for pos in range(period):
        values = sol.seasonal[pos::period]
        np.testing.assert_allclose(values, values[0], atol=1e-12, rtol=0.0)
