"""
Structured term specification for regression design matrices.

PyStatistics deliberately does not use R-style formula strings (``y ~ x``).
Instead, a model is described by a Python list of *terms*:

    - a bare ``str``            -> a numeric main effect (column used as-is)
    - ``C(name, ref=...)``      -> a categorical main effect (treatment coded)
    - a ``tuple`` of the above  -> an interaction term

Example::

    from pystatistics.regression import Design, C

    terms = ["age", C("sex", ref="F"), C("treatment", ref="A"),
             ("treatment", C("sex", ref="F"))]
    design = Design.from_datasource(ds, y="response", terms=terms)

This spec is structured data — trivially generated by a GUI and trivially
written into a copy-runnable "Show code" snippet. The expanded columns are
labeled ``sex[M]``, ``treatment[B]:sex[M]`` so coefficient output names each
factor level and interaction explicitly.

The actual factor encoding is delegated to the shared, R-validated engine in
``pystatistics.core.encoding`` (the same one ANOVA uses).
"""

from __future__ import annotations

from pystatistics.core.exceptions import ValidationError

import itertools
from dataclasses import dataclass
from typing import Any, Mapping, Sequence, Union

import numpy as np
from numpy.typing import NDArray

from pystatistics.core.encoding import encode_dummy


@dataclass(frozen=True)
class C:
    """
    Mark a column as a categorical predictor (treatment / dummy coded).

    Args:
        name: the column name in the DataSource.
        ref: the reference (baseline) level that is dropped. If None, the
            first level in sorted order is used as the baseline — matching
            R's default factor ordering and the library's ANOVA encoder.

    A factor with ``k`` levels expands to ``k - 1`` indicator columns labeled
    ``name[level]`` for each non-reference level.
    """
    name: str
    ref: str | None = None


# A single element of a term: a numeric column name or a categorical marker.
Element = Union[str, C]
# A term: a single element (main effect) or a tuple of elements (interaction).
Term = Union[str, C, tuple]


def _resolve_element(
    source: Mapping[str, Any],
    element: Element,
) -> tuple[NDArray[np.floating[Any]], list[str]]:
    """Encode one element into (columns, labels).

    A numeric element is a single column used as-is. A categorical element is
    expanded to k-1 treatment-coded indicator columns.

    Raises:
        TypeError: if element is neither str nor C.
        ValueError: if a bare (numeric) column cannot be cast to float — the
            caller must wrap genuinely categorical columns in C().
    """
    if isinstance(element, C):
        raw = source[element.name]
        if hasattr(raw, "cpu"):
            raw = raw.cpu().numpy()
        coded, levels, _baseline = encode_dummy(
            np.asarray(raw), reference=element.ref
        )
        labels = [f"{element.name}[{lvl}]" for lvl in levels]
        return coded, labels

    if isinstance(element, str):
        raw = source[element]
        if hasattr(raw, "cpu"):
            raw = raw.cpu().numpy()
        arr = np.asarray(raw)
        try:
            col = arr.astype(np.float64).reshape(-1, 1)
        except (ValueError, TypeError) as exc:
            raise ValidationError(
                f"Column {element!r} is not numeric and cannot be used as a "
                f"bare predictor. Wrap it as a categorical: C({element!r})."
            ) from exc
        return col, [element]

    raise TypeError(
        f"Term element must be a column name (str) or C(...), got "
        f"{type(element).__name__}: {element!r}"
    )


def _resolve_interaction(
    source: Mapping[str, Any],
    elements: Sequence[Element],
) -> tuple[NDArray[np.floating[Any]], list[str]]:
    """Encode an interaction term as the product of its elements' columns.

    Each element is resolved to a column block (1 column for a numeric
    predictor, k-1 for a categorical), then the interaction is the
    element-wise product across one column from each block. Numeric x numeric,
    numeric x categorical, and categorical x categorical all reduce to the
    same product.

    Column ordering matches R's ``model.matrix``: the *first* element's levels
    vary fastest, later elements slower. So for ``a:b`` with a-levels (y, z)
    and b-levels (q, r) the columns are ``a[y]:b[q], a[z]:b[q], a[y]:b[r],
    a[z]:b[r]`` — the same order R emits, so coefficient arrays line up
    position-for-position with lm/glm/coxph.
    """
    if len(elements) < 2:
        raise ValidationError(
            f"Interaction term must have at least 2 elements, got {len(elements)}"
        )

    blocks = [_resolve_element(source, e) for e in elements]
    col_blocks = [b[0] for b in blocks]
    lab_blocks = [b[1] for b in blocks]
    pcounts = [c.shape[1] for c in col_blocks]
    n = col_blocks[0].shape[0]

    out_cols: list[NDArray[np.floating[Any]]] = []
    out_labels: list[str] = []
    # itertools.product makes its LAST argument vary fastest; iterating over
    # the reversed block sizes therefore makes the FIRST element vary fastest
    # (R's convention). Reversing each combo maps it back to element order.
    for combo in itertools.product(*[range(p) for p in reversed(pcounts)]):
        idx = combo[::-1]
        col = np.ones(n, dtype=np.float64)
        for k, ik in enumerate(idx):
            col = col * col_blocks[k][:, ik]
        out_cols.append(col.reshape(-1, 1))
        out_labels.append(":".join(lab_blocks[k][idx[k]] for k in range(len(idx))))

    return np.hstack(out_cols), out_labels


def _term_display_name(term: Term) -> str:
    """Human-readable name of a term for anova/drop1 table rows."""
    if isinstance(term, tuple):
        return ":".join(_term_display_name(e) for e in term)
    if isinstance(term, C):
        return term.name
    return str(term)


def build_terms_design(
    source: Mapping[str, Any],
    terms: Sequence[Term],
    *,
    intercept: bool = True,
) -> tuple[NDArray[np.floating[Any]], list[str], list[int], list[str]]:
    """Build a numeric design matrix and aligned column labels from a term spec.

    Args:
        source: a mapping from column name to array (e.g. a DataSource).
        terms: the ordered list of terms — bare str (numeric main effect),
            C(...) (categorical main effect), or tuple of these (interaction).
        intercept: whether to prepend an intercept column. True for OLS/GLM,
            False for Cox PH (which has no intercept).

    Returns:
        ``(X, names, assign, term_names)``. ``X`` is (n, p) float64 and ``names``
        has length p, aligned column-for-column with X (when ``intercept`` is
        True, ``names[0]`` is "(Intercept)"). ``assign[j]`` is the index into
        ``term_names`` of the term that produced column j — the intercept, when
        present, is term 0 ("(Intercept)"); every subsequent term (which may span
        several dummy/interaction columns) gets the next index. This grouping is
        what ``anova``/``drop1`` use to add or drop whole terms.

    Raises:
        ValueError: empty terms, non-numeric bare column, or malformed term.
        TypeError: a term element of an unsupported type.
    """
    if not terms:
        raise ValidationError("terms must be a non-empty sequence")

    blocks: list[NDArray[np.floating[Any]]] = []
    names: list[str] = []
    assign: list[int] = []
    term_names: list[str] = []
    n: int | None = None

    if intercept:
        # n is unknown until the first column is resolved; defer the intercept
        # column to the end and stitch it in front once we know n.
        names.append("(Intercept)")
        term_names.append("(Intercept)")

    base_term = 1 if intercept else 0
    for k, term in enumerate(terms):
        if isinstance(term, tuple):
            cols, labels = _resolve_interaction(source, term)
        else:
            cols, labels = _resolve_element(source, term)

        if n is None:
            n = cols.shape[0]
        elif cols.shape[0] != n:
            raise ValidationError(
                f"Term produced {cols.shape[0]} rows, expected {n}"
            )
        blocks.append(cols)
        names.extend(labels)
        term_names.append(_term_display_name(term))
        assign.extend([base_term + k] * cols.shape[1])

    if n is None:
        raise ValidationError("terms produced no columns")

    if intercept:
        blocks.insert(0, np.ones((n, 1), dtype=np.float64))
        assign.insert(0, 0)

    X = np.hstack(blocks)
    return X, names, assign, term_names
